#index:
#    path: /
#    controller: App\Controller\DefaultController::index

author_login_check:
  path: /author-login-check

author_logout:
  path: /author-logout

admin_login_check:
  path: /admin-login-check

admin_logout:
  path: /admin-logout